### ISSUE TITLE
Add full-range of options for the Server.cfg

### ISSUE THREAD

**Issue by MajorMittenss** [Dahlgren/arma-server-web-admin#101]
Please add the full range of options available in the server.cfg as the [wiki](https://community.bistudio.com/wiki/server.cfg) Or add some of the slightly more important ones like 
"Servercommandpassword"
"loopback"
"kickduplicate"

My only hurdle with ditching windows lies upon the servercommandpassword and I haven't found a way to define it manually ;) 

Thanks in advance

**Comment by Dahlgren** [comment]
If you can specify which specific options you are lacking I can probably add it

**Comment by MajorMittenss** [comment]
@Dahlgren 
Servercommandpassword is the one I'm lacking
Loopback and kickduplicate would be a bonus if added, thanks.

**Comment by Dahlgren** [comment]
Shouldn't be too hard then, just need to add the new values which didn't exist before to the underlying server process handler first then
