### ISSUE TITLE
Not Working on Windows

### ISSUE THREAD

**Issue by shadez95** [Dahlgren/arma-server-web-admin#107]
I followed the instructions to test in Windows, and have had no success. I get this in powershell...
```
Could not load any existing servers configuration, starting fresh
```
When I attempt to view the web interface at http://localhost:3000 I get no response.

**Comment by shadez95** [comment]
My [config.js](https://gist.github.com/shadez95/bdb4ece4b0929095aa6e37280f56d10c)

**Comment by Dahlgren** [comment]
- Are there any issues logged to the console?
- Is your current node.exe allowed access through the firewall?
- What error are you getting when fetching http://localhost:3000?

We use this tool on multiple Windows servers without any issues

**Comment by shadez95** [comment]
I figured it out. When using basic auth, it doesn't start. I had a username and password filled in for basic auth and that's what was causing the server to not start.

**Comment by shadez95** [comment]
Closing since the issue was resolved.
