### ISSUE TITLE
Delete/Stop with confirmation

### ISSUE THREAD

**Issue by NemesisRE** [Dahlgren/arma-server-web-admin#12]
At the moment the "Delete" Button does what it should but without confirmation which is leads to a high risk of deleting things which you didn't wanted.
The same goes for Server "Stop" button.

A confirmation dialog would be nice.

**Comment by Dahlgren** [comment]
I've been planning to add https://lipis.github.io/bootstrap-sweetalert/ for any destructive addons

**Comment by NemesisRE** [comment]
That looks nice.

**Comment by NemesisRE** [comment]
Looks great, thank you. Keep up the good work.
