### ISSUE TITLE
Unable to Start Arma On New Install

### ISSUE THREAD

**Issue by aristenn** [Dahlgren/arma-server-web-admin#123]
Hello,

I just recently did a fresh install of my community's arma server and decided to use this panel to manage our servers.

I have arma installed and it runs when I click on the arma3server.exe manually, an Arma server launches as I expected and clients are able to connect. 

When I attempt to launch a server via the control panel:
- An Arma3 process starts
- The panel says the server is launching
- I get an error message on the remote server: "Unable to locate a running instance of Steam" (See screenshot)
- When clicking on 'OK', the process is terminated

![arma server start error](https://user-images.githubusercontent.com/17153453/46920130-38902f80-cfaf-11e8-84c8-096ce0d52486.PNG)

**Comment by Fusselwurm** [comment]
> • An Arma3 process starts

so… arma3.exe instead of arma3server.exe?

**Comment by aristenn** [comment]
I'm not sure what it was doing before. 

Prior, I was using a relative path in config,js (../../../Games/ArmA3), but I changed it to an absolute path (D:\\Games\\ArmA3) and now I am no longer having the error. The server starts up as expected and clients can connect and play.

I am going to close this ticket, as I am no longer having a problem.

**Comment by Dahlgren** [comment]
`/` is not a valid path separator for Windows, `\\` must be used. Absolute paths overall works better, a relative one with correct path separator might've worked 🤔 

Great that you got it working!
