### ISSUE TITLE
Upload mission module not secure

### ISSUE THREAD

**Issue by ton2142** [Dahlgren/arma-server-web-admin#124]
I just test put file jpg in module upload mission this file can upload in server then
hacker can upload file shell script ,I think you must fix it
ref https://www.owasp.org/index.php/Unrestricted_File_Upload

**Comment by Dahlgren** [comment]
Uploaded files are not executed by the manager so there is no server side execution of the files. I don't think Arma would load anything other than a pbo or unpacked mission file?

The manager is also intended to be locked down, for example with the built in HTTP Basic Auth. If a hacker gets access to your credentials that is of course bad in many other ways.

Restricting to pbo files is of course possible, there is currently no support for uploading an extracted mission as mission.sqm anyway.

If unpacked missions, or mods, could be uploaded that would require unrestricted file upload.

**Comment by Dahlgren** [comment]
Only .pbo files will now be moved to mpmissions folder
