### ISSUE TITLE
Search Mod-directories recursively

### ISSUE THREAD

**Issue by Krzmbrzl** [Dahlgren/arma-server-web-admin#133]
All specified mod-directories should be searched recursively. That is if I specify a mod-folder `myMods` and I have a mod at `MyMods/MyAwesomeModset/@MyMod`, it should also be found and displayed in the GUI.

**Comment by Frozen-byte** [comment]
Linux-Only implementation in my Fork: 
https://github.com/Frozen-byte/arma-server-web-admin/commit/f17c52d33955c13496de053d2c288399fab8365b
