### ISSUE TITLE
Error when starting a server - Docker on OMV

### ISSUE THREAD

**Issue by ryanparsons7** [Dahlgren/arma-server-web-admin#136]
I've setup via Docker on a OMV server. Followed instructions and got the WebUI loading and working. However, when i create a server and press "Start", nothing happens and logs the following in the container log:
![image](https://user-images.githubusercontent.com/13571100/56807856-e23a5e00-6827-11e9-9986-5be667c9768f.png)

I've setup the shared folders for the container and checked that the Arma 3 Server path is linked correctly, the user that the container is using has full permissions to that folder, but sadly the issue still persists.

Any help would be appreciated, thank you.

**Comment by Dahlgren** [comment]
My guess is wrong path to arma3 directory or wrong type specified. What does your config.js and docker setup look like?

**Comment by ryanparsons7** [comment]
Here's my settings for the docker container.
![image](https://user-images.githubusercontent.com/13571100/56854557-7bed3280-6930-11e9-8b8c-fffbcc4e98ce.png)
![image](https://user-images.githubusercontent.com/13571100/56854571-9fb07880-6930-11e9-875e-1bbef2990cf7.png)

Nothing is entered in the extra arguments or container commands section. I have a shared folder for the server through OMV that allows everyone read/write/execute just to get it working. Using a SteamCMD container that is also mounted to that folder to pull the server files from the steam servers.

Here's the shared folder:
![image](https://user-images.githubusercontent.com/13571100/56854617-590f4e00-6931-11e9-86c2-5afd6ef304fb.png)

Where would I find this "config.js" file?

**Comment by Dahlgren** [comment]
That looks correct, the config.js file is autogenerated by the container. And type and path looks correct too.

Is `arma3server` in that folder executable by all users?

**Comment by Dahlgren** [comment]
Issue resolved using Discord, OMV mounts shared folders as `noexec` by default
