### ISSUE TITLE
Support new config elements

### ISSUE THREAD

**Issue by formtapez** [Dahlgren/arma-server-web-admin#137]
Can we have support for new elements of the config file since ArmA 1.90 like:
- kickTimeout
- votingTimeOut
- roleTimeOut
- briefingTimeOut
- debBriefingTimeOut
- lobbyIdleTimeout
?

And a free text box which contents gets added to the config would be nice.

**Comment by Dahlgren** [comment]
Sorry, I forgot to make these changes public. The underlying library is updated, will make public ASAP, https://github.com/Dahlgren/node-arma-server/pull/29

**Comment by Dahlgren** [comment]
Branch and PR with new functionality is up. Feel free to try it out if you want to. I'll test it a bit on our linux and windows servers before merging to master. I'll rebase the steam workshop branch as well afterwards.

**Comment by formtapez** [comment]
It works as expected.
Thank you!

**Comment by Dahlgren** [comment]
Fixed with #138
