### ISSUE TITLE
SteamCmd needs to be installed

### ISSUE THREAD

**Issue by Barbaricbuffalo** [Dahlgren/arma-server-web-admin#139]
Either Im missing something or something. I am trying to install mods on my server via the web app but it keeps crashing it saying SteamCmd needs to be installed. Well I have tried changing the steam path to steam cmd and it doesn't show my workshop folder and still crashes it. I have looked around if there was a place to dictate where my steam cmd install was but i found nothing.  So i was just wondering if you could how. Oh yah, im running this on linux server, everything else works and when i have it set up i can see mods inside of my workshop folder.

**Comment by Dahlgren** [comment]
This is just a log message that steamcmd will be installed by the application.

Are there any other output by the application which could give any hints as to what your issue is?

The steam path should be to where you want you workshop mods to be downloaded and stored.

**Comment by Dahlgren** [comment]
Probably related to issue with unzip, https://github.com/Dahlgren/node-steamcmd/pull/2

If issue still remains please open the ticket again
