### ISSUE TITLE
Steam Workshop Functionality

### ISSUE THREAD

**Issue by canuckbrian** [Dahlgren/arma-server-web-admin#157]
I came across your project here and I'm trying to get it to work on my linux server so me and my friends can manage our private Arma 3 server.

- Arma 3 Server installed at ~/a3server
- Arma 3 Server runs if manually started using a test mission
- NPM 14.x installed
- Git Clone of Master branch of 'arma-server-web-admin'
- Configured config.js with paths and credentials
- 'npm install' completed
- Installed Systemd service script, enabled, and started the service
- Can access the web interface

What I'm experiencing is:
- No button for searching or downloading MODs from Workshop as shown in screenshots
- Unable to download mission by providing Workshop ID, no error message displayed

Hoping you can provide some insight into how to get this to work. Would be really appreciated.

Thanks!

**Comment by Frozen-byte** [comment]
Do you get any errors in the Web console? (by default it's F12 on Firefox or Chrome)

You should be able to see the "Workshop" Functionality only for Missions, yet.

**Comment by Dahlgren** [comment]
master branch does not contain the steam workshop functionality. See https://github.com/Dahlgren/arma-server-web-admin/issues/28#issuecomment-434070420

**Comment by canuckbrian** [comment]
I have used the WIP branch you mentioned and it works. For both MOD and Mission download.

Thanks
