### ISSUE TITLE
Linux x64

### ISSUE THREAD

**Issue by kkotowick** [Dahlgren/arma-server-web-admin#162]
First off, thank you for the great work on this tool.

I saw your recent commit to add support for x64 on Linux (https://github.com/Dahlgren/arma-server-web-admin/commit/d51a1a4208d5aaf947a3b2f15c1bf389c4deff72). Could you provide any info on how to get that working? I tried selecting "arma3_x64" on Linux and it threw an error about not finding the executable. Where does one actually obtain the x64 Linux dedicated server executable?

**Comment by Dahlgren** [comment]
Linux x64 server is currently on available on the `development` and `profiling` branches, https://community.bistudio.com/wiki/Arma_3_Steam_Branches

`profiling` is compatible with the regular client and is therefor easier to use.

You can download the profiling branch using either the regular Steam client or steamcmd with `app_update 233780 -beta profiling -betapassword CautionSpecialProfilingAndTestingBranchArma3 validate`

**Comment by kkotowick** [comment]
@Dahlgren Thanks! Any chance of getting a branch merge so we can use Linux x64 with the steam workshop for mods branch?

**Comment by Dahlgren** [comment]
Sure! Both of them are rebased on top of master now
