### ISSUE TITLE
Add missions to rotation with default difficulty

### ISSUE THREAD

**Issue by kkotowick** [Dahlgren/arma-server-web-admin#165]
Currently, all missions that are added to a server's rotation are added with the "Recruit" difficulty. I think it would be preferrable if they were added with the "Difficulty" value that is selected on the "Settings" page for the server, as this would prevent groups from accidentally starting their group event servers on Recruit.

**Comment by Frozen-byte** [comment]
This happened to me a million times, at least. I hard-coded the difficulty to "Custom" as every known dedicated server runs.

See: https://github.com/Dahlgren/arma-server-web-admin/commit/26eb4f0febdcd73cf98980a20115d00bb1a40429
