### ISSUE TITLE
Sort logs by descending date and paginate

### ISSUE THREAD

**Issue by Dystroxic** [Dahlgren/arma-server-web-admin#167]
On a Linux server, there's no limit to the number of .rpt files there can be (unlike Windows, it doesn't delete old ones). Therefore, the "Logs" page can have hundreds of log files, and the one you're looking for (most recent) is at the very bottom.

It would be great if there could be sorting of the files by newest-first (or better yet, optional sort by each column), and pagination of logs (or only loading the most recent N logs, with N being a setting in `config.js`).

**Comment by Frozen-byte** [comment]
This may temporarily help you; while waiting for a proper fix: Make use of the Linux `logrotate` program to keep the folder slim.
