### ISSUE TITLE
Cannot download mods from the workshop.

### ISSUE THREAD

**Issue by teemo0803** [Dahlgren/arma-server-web-admin#168]
![image](https://user-images.githubusercontent.com/49296645/90317127-d103ec00-df59-11ea-9ff5-40aed0e17dec.png)

**Comment by Frozen-byte** [comment]
You may have a look for your issue:  
here (original issue) https://github.com/Dahlgren/arma-server-web-admin/issues/28
and here (newer duplicate) https://github.com/Dahlgren/arma-server-web-admin/issues/157

TL;DR:
The functionality was not released, yet please check out the WIP feature branch: `feature/steam-workshop-mods-status`

**Comment by teemo0803** [comment]
Cheers
