### ISSUE TITLE
Unable to download mods

### ISSUE THREAD

**Issue by CCVia** [Dahlgren/arma-server-web-admin#169]
Hello,

I was using the master branch but I've switched to "/steam-workshop-mods-status" because I wanted to try the mod download feature. 

I don't know if I have something wrong on my config, a permissions issue or anything like that, but I can't download anything from the workshop. I get this error:

```
stdout: Logged in OK
Waiting for user info...
stdout: OK
Downloading item 751965892 ...
ERROR! Download item 751965892 failed (Failure).CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.

```

This is my config.js file:

```

module.exports = {
  game: 'arma3', // arma3, arma2oa, arma2, arma1, cwa, ofpresistance, ofp
  path: '/home/user/arma3folder/',
  port: 3000,
  host: '123.123.123.123', // Can be either an IP or a Hostname
  type: 'linux', // Can be either linux, windows or wine
  additionalConfigurationOptions: '', // Additional configuration options appended to server.cfg file
  parameters: [ // Additional startup parameters used by all servers
    '-noSound',
    '-world=empty'
  ],
  serverMods: [ // Mods used exclusively by server and not shared with clients

  ],
  steam: {
    apiKey: 'MYAPIKEY', // https://steamcommunity.com/dev/apikey
    path: '/home/user/arma3folder/',
    username: 'STEAM-USER',
    password: 'STEAM-PASSWORD',
  },
  admins: [], // add steam IDs here to enable #login without password
  auth: { // If both username and password is set, HTTP Basic Auth will be used. You may use an array to specify more than one user.
    username: 'ADMIN', // Username for HTTP Basic Auth
    password: 'PASSWORD', // Password for HTTP Basic Auth
  },
  prefix: "", // Prefix to all server names
  suffix: "", // Suffix to all server names
  logFormat: "dev", // expressjs/morgan log format
};

```

By the way, this is an awesome project! The main branch is amazing, only the modules part is missing. In the steam-workshop-mods-status branch they keep themselves updated? Do I have to remove the capital letters of the modules to avoid problems? These two points are the only ones I find missing from the main branch (and perhaps an indicator of the remaining available hard drive).

**Comment by Frozen-byte** [comment]
Does the *user*, which runs your nodeServer have write-access to the `/home/user/arma3folder/` folder?

**Comment by CCVia** [comment]
Thank you!

Everything is owned by "user", and I'm launching with "npm start" with that very same user. I don't know how to check wich user runs nodeServer, but I bet is the same one.

In my config.js file I have 2 lines with a path, both set to "/home/user/arma3folder/". Is this allright?

**Comment by Dahlgren** [comment]
Is Arma 3 owned by the Steam user account used for downloads?

**Comment by CCVia** [comment]
> 
> 
> Is Arma 3 owned by the Steam user account used for downloads?

No, I guess might be this. I have a separate account just for the Arma Server and steamcmd (as described on Arma 3 Server docs). Do I need to own Arma on this account to be able to subscribe to Workshop content?

**Comment by Dahlgren** [comment]
Yep, only accounts that owns Arma 3 are allowed access to Arma 3 Workshop files

**Comment by CCVia** [comment]
> 
> 
> Yep, only accounts that owns Arma 3 are allowed access to Arma 3 Workshop files

Problem solved then, it was that. Thank you so much for your help! I don't think using my own account on a server is a good idea. I guess I'll be switching to the main branch again. 

If I purchase another copy of the game to use on the server and keep using this branch, the mods would be updated automatically? Would I have to change all file names to lowercase manually? Those two things are the ones that made me take a look at this branch; it's no much of a hassle to upload the mods from my computer, but maintenance is a drag.

**Comment by Dahlgren** [comment]
Mods show as outdated when workshop data is refreshed and can be selected for update when admin thinks it's applicable. Automated update is impractical as Windows won't be happy with files being changed while used by an active running server.

**Comment by CCVia** [comment]
> 
> 
> Yep, only accounts that owns Arma 3 are allowed access to Arma 3 Workshop files

Problem solved then, it was that. Thank you so much for your help! I don't think using my own account on a server is a good idea. I guess I'll be switching to the main branch again. 

If I purchase another copy of the game to use on the server and keep using this branch, the mods would be updated automatically? Would I have to change all file names to lowercase manually? Those two things are the ones that made me take a look at this branch; it's no much of a hassle to upload the mods from my computer, but maintenance is a drag. 





> 
> 
> Mods show as outdated when workshop data is refreshed and can be selected for update when admin thinks it's applicable. Automated update is impractical as Windows won't be happy with files being changed while used by an active running server.

That's really nice, thanks. What about the capital letters? Some mods don't work properly if those are used.

**Comment by Dahlgren** [comment]
Currently no changes are done to steam workshop data to avoid breaking steamcmd

**Comment by CCVia** [comment]
That's understandable, but some mods like Alive won't work on linux servers. I'm gonna switch to the main branch for now and I'll keep an eye on any future changes. 

Thanks again for your help and congratulations on this project!
