### ISSUE TITLE
[Feature Request] Ability to host from Apache or similar instead of internal webserver

### ISSUE THREAD

**Issue by Freddo3000** [Dahlgren/arma-server-web-admin#171]
Title, would be useful to be able to host via (as an example) `abc.com/armaadmin/` instead of `abc.com:12345myport`, as well as the ability to use HTTPS, amongst other benefits.

**Comment by NocFA** [comment]
You could just reverse proxy via Apache, which, is what I've done to enable the panel on my domain with SSL.

**Comment by Dahlgren** [comment]
Duplicate of #170 

As mentioned there, you can also use a subdomain i.e. `arma.abc.com` -> `localhost:12345`

**Comment by Dahlgren** [comment]
Here's an example of reverse proxy config for apache to get you started, https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension
