### ISSUE TITLE
Download hidden/excluded/friends Workshop items

### ISSUE THREAD

**Issue by CCVia** [Dahlgren/arma-server-web-admin#179]
It's a really small thing, but it would be great to have a way to download items excluded from the general search in Steam Workshop. Maybe using Steam Workshop ID like in the download missions feature?

For example, I can't download this map because is hidden: https://steamcommunity.com/workshop/filedetails/?id=843362862

I've tried subscribing to it and downloading it with steamcmd but it still doesn't show at the list of available mods on the panel. The mod is at the same folder than the others and this is his meta.cpp (just in case):

```
protocol = 1;
publishedid = 0;
name = "Reshmaan Province [3CB]";
timestamp = 5247887170352625754;
```

I don't know if it's possible to manually upload a mod when using the steam-workshop-mods-status branch. I guess it would be a workaround to the problem.

**Comment by Dahlgren** [comment]
Downloading a specific workshop ID is possible via the API today. I've planned to add a button for it but never got around to. I guess it would be easy for me to add.

**Comment by CCVia** [comment]
Great! If it's not too much trouble, keep this in mind for the next update.

Any idea on why the mods downloaded via steamcmd are not showing on the panel?

The other way would be uploading the mod manualy like when using the main branch, but i don't think I can do that on the steam-workshop-mods-status branch, right? That mod wouldn't show on the panel's mod list if I were to upload it on the game directory.

**Comment by Dahlgren** [comment]
Added extra button to download specific workshop id in addition to search
