### ISSUE TITLE
Race condition when launching server

### ISSUE THREAD

**Issue by Tirpitz93** [Dahlgren/arma-server-web-admin#184]
Hello again,
Another issue I encountered (not virtual server branch), when launching a server with headless clients, sometimes the HCs launch first and never release the cache lock. this means the server never starts.

**Comment by Dahlgren** [comment]
Interesting. Some HC regressions were introduced around Arma 3 patch 1.96 or 1.98. If the server is not yet fully launched when they try to connect they can get stuck in connecting state.

**Comment by Tirpitz93** [comment]
would it be possible to delay HC launch till after server is up?

**Comment by Dahlgren** [comment]
Ideally it would probably wait until steam queries starts responding, should be quite simple to delay the launch there.

I've also had some ideas around letting HCs be dynamically changed during mission if there's a need for fewer/more.

We've sometimes had issues were a mission maker decided to have too many HCs which backfired mid mission. Or forgotten to launch the server with HCs. Being able to scale up/down would solve solve such issues.

**Comment by Tirpitz93** [comment]
> Ideally it would probably wait until steam queries starts responding, should be quite simple to delay the launch there.
> 
that is what I was thinking, I am not sure what logic the panel currently uses for up detection. but that would probably be sufficient.

> I've also had some ideas around letting HCs be dynamically changed during mission if there's a need for fewer/more.
> 

Sounds interesting, its not something we have come across, at least not regularly


> We've sometimes had issues were a mission maker decided to have too many HCs which backfired mid mission. Or forgotten to launch the server with HCs. Being able to scale up/down would solve solve such issues.
cant you just kick the HC?

**Comment by Tirpitz93** [comment]
I was only able to reproduce the error on my local machine when loading significant amounts of mods.
when loading a vanilla server is seems to load fine

**Comment by Tirpitz93** [comment]
Seems to only on be an issue on performanceandprofiling

**Comment by Dahlgren** [comment]
We've been able to repro it with the 2.04 perf binary, I'll make some changes to the startup order
