### ISSUE TITLE
Using CDLC in steam-workshop-mods

### ISSUE THREAD

**Issue by Uncle-Sagbag** [Dahlgren/arma-server-web-admin#193]
Hello Dahlgren,

I've been using the steam-workshop-mods branch for a while now and it fits all my needs. However, my unit has been asking to use CDLC, especially the new Prairie Dog CDLC. I noticed your master branch has received a commit to allow loading of CDLC. Is there any chance of a similar commit to the steam-workshop-mods branch?

**Comment by Dahlgren** [comment]
You can use the Compatibility data mods from Steam Workshop as workaround

Global Mobilization: https://steamcommunity.com/sharedfiles/filedetails/?id=1776428269
S.O.G. Prairie Fire: https://steamcommunity.com/sharedfiles/filedetails/?id=2477276806

**Comment by Uncle-Sagbag** [comment]
Yep, that worked. Another method would be to add `-mod=vn;` to the start up parameters. I stuck with the second option.
![image](https://user-images.githubusercontent.com/84741883/120704279-6722e780-c484-11eb-9b67-82506c44ecd6.png)

For anyone reading this ticket, make sure to change the owner and group of the `vn` folder from root to the user after using steamcmd. It would not see the folder if it is owned by root.
