### ISSUE TITLE
Timezone and naming of logfiles

### ISSUE THREAD

**Issue by formtapez** [Dahlgren/arma-server-web-admin#196]
In [lib/logs.js](https://github.com/Dahlgren/arma-server-web-admin/blob/977f24c45182f43d43f76e78a6ca841f041bec0b/lib/logs.js#L24) `Date().toISOString()` is used to generate a datestring for the logfiles. The timezone for it is always UTC. Could we have a local timezone here?

Also: What happens when you enable multiple servers for autostart? Will multiple logfiles "collide" with each other because of a same name? As a solution could we have the filename suffixed with the actual servername?

**Comment by Dahlgren** [comment]
Please leave feedback here https://github.com/Dahlgren/arma-server-web-admin/pull/180

**Comment by formtapez** [comment]
That doesn´t cover any of two issues.

**Comment by Dahlgren** [comment]
Fixed in #197 and #198

**Comment by formtapez** [comment]
#197 works great, thanks.
#198 I would prefer to have the correct timestamp in the filename itself.

**Comment by Dahlgren** [comment]
UTC is the most correct as admins might be from multiple timezones
