### ISSUE TITLE
Windows Server Not Starting

### ISSUE THREAD

**Issue by Lyderian** [Dahlgren/arma-server-web-admin#203]
Howdy,
Trying this out, new to node js. Having an issue whenever I hit start server the server does not launch and the web panel crashes.

Here is my log

[2021-10-10T01_39_11_313Z-debug.log](https://github.com/Dahlgren/arma-server-web-admin/files/7316685/2021-10-10T01_39_11_313Z-debug.log)

Here is my config

> module.exports = {
  game: 'arma3_x64', // arma3, arma2oa, arma2, arma1, cwa, ofpresistance, ofp
  path: 'S:\Steam\Servers\arma3\',
  port: 3000,
  host: '192.168.1.64', // Can be either an IP or a Hostname
  type: 'windows', // Can be either linux, windows or wine
  additionalConfigurationOptions: '', // Additional configuration options appended to server.cfg file
  parameters: [ // Additional startup parameters used by all servers
    '',
    '-world=empty'
  ],
  serverMods: [ // Mods used exclusively by server and not shared with clients
    '',
    '',
  ],
  steam: {
    apiKey: 'thisisalsofilled', // https://steamcommunity.com/dev/apikey
    path: 'S:\Steam\Steam',
    username: 'thisisfilled',
    password: 'soisthis',
  },
  admins: [], // add steam IDs here to enable #login without password
  auth: { // If both username and password is set, HTTP Basic Auth will be used. You may use an array to specify more than one user.
    username: 'admin', // Username for HTTP Basic Auth
    password: 'wonderfull', // Password for HTTP Basic Auth
  },
  prefix: "", // Prefix to all server names
  suffix: "", // Suffix to all server names
  logFormat: "dev", // expressjs/morgan log format
};

Any help you could provide would be greatly appreciated.

**Comment by Lyderian** [comment]
Disregard figured it out. Paths need to be fixed with "\\"

IE: S:\\Steam\\Servers\\arma3

**Comment by Dahlgren** [comment]
I'll update the readme with a Windows example, this seems to be happening quite often
