### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by diaverso** [Dahlgren/arma-server-web-admin#222]
When trying to load some mods, I get this error. and the server does not start

19:50:33 SteamAPI initialization failed. Steam features won't be accessible!
19:50:33 Initializing stats manager.
19:50:33 Stats config disabled.
19:50:33 sessionID: 36c58f828ea3fd874368eaae03c9d6afa427df70
ErrorMessage: Cannot open file '/home/arma3/arma3/@VSM All-In-One Collection\addons\arid_vests'
Application terminated intentionally
19:50:33 ../lib/Network/networkServer.cpp ClearNetServer:NOT IMPLEMENTED - briefing!
Cannot open file '/home/arma3/arma3/@VSM All-In-One Collection\addons\arid_vests'
19:50:33 Critical:Destroying running thread!
19:50:33 Critical:Destroying running thread!
19:50:33 Critical:Destroying running thread!
19:50:33 Critical:Destroying running thread!
19:50:33 Critical:Destroying running thread!
19:50:33 Critical:Destroying running thread!
19:50:33 Critical:Destroying running thread!

**Comment by Dahlgren** [comment]
Arma 3 linux server requires `addons` folder to be lower case and all PBO files inside that folder to also be lower case. Otherwise loading of those PBO(s) will fail.

**Comment by Frozen-byte** [comment]
To make all folders LC, you may navigate into the `addons` folder and execute the following command: `#find . -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;`
