### ISSUE TITLE
Cant start the Server 

### ISSUE THREAD

**Issue by ManfredDoorstander** [Dahlgren/arma-server-web-admin#226]
Every time i start the server it instantly closes and stops.

The is the log:

20:08:29 SteamAPI initialization failed. Steam features won't be accessible!
20:08:29 Initializing stats manager.
20:08:29 Stats config disabled.
20:08:29 sessionID: 8d9bded42d48637d4a669afbd728f11ef8f3494d
ErrorMessage: Cannot open file '/home/arma3/@WebKnights Footsteps\addons\gog_wbk_footsteps'
Application terminated intentionally
20:08:29 ../lib/Network/networkServer.cpp ClearNetServer:NOT IMPLEMENTED - briefing!
Cannot open file '/home/arma3/@WebKnights Footsteps\addons\gog_wbk_footsteps'
20:08:29 Critical:Destroying running thread!
20:08:29 Critical:Destroying running thread!
20:08:29 Critical:Destroying running thread!
20:08:29 Critical:Destroying running thread!
20:08:29 Critical:Destroying running thread!

It says something about the "SteamAPI" but i searched everywhere and found nothing to fix it, an someone help me with this?

**Comment by Dahlgren** [comment]
Arma Linux server required PBO filenames to be lowercase as well as `addons` folder name. Make sure permissions are correct as well.

**Comment by ManfredDoorstander** [comment]
and where can i find the pbo files?

The Addons fodler is lower case

**Comment by ManfredDoorstander** [comment]
is there a way to make them all lower case at once or do i need to do them on at a time?

**Comment by Dahlgren** [comment]
You can find instructions on the Bohemia wiki, https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server#Case_sensitivity_.26_Mods

**Comment by ManfredDoorstander** [comment]
i cant figure ot the command

**Comment by ManfredDoorstander** [comment]
the command doesnt work

**Comment by Dahlgren** [comment]
Don’t forget to install the correct`rename` package depending on your Linux dist
