### ISSUE TITLE
Steam API failed

### ISSUE THREAD

**Issue by ManfredDoorstander** [Dahlgren/arma-server-web-admin#227]
Ever time I start the server with mods it says „ SteamAPI initialization failed. Steam features won't be accessible!“

can someone help me fix it?

**Comment by Dahlgren** [comment]
That’s normal and expected for a server since you don’t have the entire desktop client running

**Comment by ManfredDoorstander** [comment]
But my server crashes every time

**Comment by ManfredDoorstander** [comment]
Here is the Log:
„ 23:54:14 SteamAPI initialization failed. Steam features won't be accessible!
23:54:14 Initializing stats manager.
23:54:14 Stats config disabled.
23:54:14 sessionID: 4c351b88f7329aeacd7513440c4aa9934bf9fd8c
ErrorMessage: Cannot open file '/home/arma/arma/@tfc_core\addons\night_vision'
Application terminated intentionally
23:54:14 ../lib/Network/networkServer.cpp ClearNetServer:NOT IMPLEMENTED - briefing!
Cannot open file '/home/arma/arma/@tfc_core\addons\night_vision'
23:54:14 Critical:Destroying running thread!
23:54:14 Critical:Destroying running thread!
23:54:14 Critical:Destroying running thread!
23:54:14 Critical:Destroying running thread!“

**Comment by Dahlgren** [comment]
Arma Linux server requires all PBO file names to be lower case. Either contact the mod author to fix it or rename the files yourself

**Comment by ManfredDoorstander** [comment]
Oh ok thx
