### ISSUE TITLE
Main version + linux server + npm -> Issue on mods

### ISSUE THREAD

**Issue by Marco674** [Dahlgren/arma-server-web-admin#238]
Hi There,
I'm running the main version on linux server and with npm (no docker)
I have issue with mods : 
After moving my mods in arma3 folder to be detected i have to rework the folders:
To be detected by arma mods have to be like that : 
@mod/addons 

Some mods are named with Addons folder (uppercase A) and is not detected in the mods tab

Can you look forward to allow folder with upercase A to be in mods tab ?

**Comment by Dahlgren** [comment]
The actual arma server linux binary requires all mod folders to have `addons` in lower case so for the server to be able to use your mods it must be lowercased.

**Comment by Marco674** [comment]
Understood, no issue so :)
