### ISSUE TITLE
Auto Restart / Bepath

### ISSUE THREAD

**Issue by Marco674** [Dahlgren/arma-server-web-admin#24]
Hi,

Can you implement a system to restart the servers at a specific time ?

I don't know if its possible to do.

Thx Also for the soft ;)

**Comment by Marco674** [comment]
Hi again, i have another idea or question

How can i define the -bepath of my servers ?
Or is it possible to add box to add the -bepath for each server ?

**Comment by Dahlgren** [comment]
Auto restart seems to be the same as #7 

I could add the ability to manually specify additional startup arguments where it would be possible to add such things as bepath.

Out of curiosity, what are the advantages or manually specifying the bepath? :)

**Comment by Marco674** [comment]
Thank's for fast answer.

To use a RCON each server needs to have the port and ip specified in Beserver.cfg

So for each of my game servers i have specified all the informations for rcon and added befilters to securise.

But my servers dont use same game modes so befilters needs to be differents that's why i have multiple battleeye forlders.

**Comment by Dahlgren** [comment]
I see, that makes sense then :)

I'll see if I can fix it soon, shouldn't be to hard since I've already added support for additional parameters. Might as well add support for shared parameters in the config file too for things such as `-noSound` etc

**Comment by Marco674** [comment]
To my mind having a text box where we will be able to add the options we want could be really awesome but idk if its possible for you

**Comment by Dahlgren** [comment]
Yeah, it will be something like that, at least for server specific parameters

**Comment by Marco674** [comment]
Perfect !

**Comment by Dahlgren** [comment]
I've created a ticket that will show progress for adding additional startup parameters, #25
