### ISSUE TITLE
Spawn multiple headless clients

### ISSUE THREAD

**Issue by Dahlgren** [Dahlgren/arma-server-web-admin#39]
Instead of just having a checkbox and creating one headless client, allow users to select the number of clients to spawn

**Comment by ToasterBR** [comment]
@Dahlgren , just to check, this is still planned?

Sorry to brought this up. I don't want to push you or anything. The thing is: I was playing some Liberation and every time I have to manually start 3 HCs. This would be a very welcome feature 👍 

Cheers!

**Comment by Dahlgren** [comment]
Yes!

I will try to do it soon, other have requested it too and we need it for our community as well 🙃

**Comment by ToasterBR** [comment]
Thank you, @Dahlgren!

Cheers!

**Comment by Dahlgren** [comment]
Tested it somewhat at least, I hope it should work fine :)

Steam branch has been rebased to include headless client changes

**Comment by ToasterBR** [comment]
Your're a GOD!

Thank you very much, sir!
