### ISSUE TITLE
Trouble launching server on windows

### ISSUE THREAD

**Issue by flexgrip** [Dahlgren/arma-server-web-admin#42]
Hey man,

The linux version worked great. But I'm trying to use this tool to launch on our windows server. Everything seems to be working. I can see the app, add the server, mods, etc.

However, now that it's all configured, when I click start, nothing happens. And I can't see any logs that would tell me why. It's definitely not launching the executable because there's no rpt file.

Is there maybe a step missing from the readme? Do I have to install the windows service or something? The api request is returning 200, so it's just failing to start the server.

I'll try putting some log messages in lib/server.js to see how far it gets. Let me know if you have any suggestions.

Also, you may want to add to the readme for windows that you have to globally install gyp and the windows build tools or else the app won't run. And again, great work man. This thing is awesome and very few lines of code ;)

**Comment by Dahlgren** [comment]
Did you switch to x64 version? Cause Steam won't automatically install the needed dependencies. You'll need to install x64 version of `Visual C++ Redistributable Packages for Visual Studio 2013` from https://www.microsoft.com/en-us/download/details.aspx?id=40784

And no, you don't have to install gyp or the windows build tools, those warnings can be ignored.

**Comment by flexgrip** [comment]
Hmm, I tried both arma3 and arma3_x64 in the config. Same result. I'll try installing that and I'll triple check that I can launch from TADST too.

npm install failed with errors, not warnings on a fresh windows server install. At least until I installed the microsoft build tools, which required gyp. Also I had to change a setting in npm to use the 2015 version from the gyp docs. It's all in there. I couldn't see or launch the server until I got rid of the npm errors from the missing ms build tools. 

Thanks for your help.

**Comment by flexgrip** [comment]
Hell yeah, I figured it out. You do need this for 64bit: https://www.microsoft.com/en-us/download/details.aspx?id=40784

Also, on a raw windows 2012 box, you need to re-install directx from the web installer. I guess windows servers is missing some dll's from the full directx install. So this had nothing to do with your app.

Thanks again. You can close this.

**Comment by Dahlgren** [comment]
Fixed the issues regarding gyp and Windows build tools! :)
