### ISSUE TITLE
Implement a Security Check via Password or IP

### ISSUE THREAD

**Issue by m1ndgames** [Dahlgren/arma-server-web-admin#5]
Maybe i just didnt find it, but is there no password auth?

**Comment by Dahlgren** [comment]
No, there is currently no auth. It's possible to run it behind a proxy which does the Auth (doable with nginx, apache etc) and have that handle the auth. I can add optional username + password setting to the config.

**Comment by Dahlgren** [comment]
HTTP Basic Auth added to config. New key auth has the values username and password. When both are set Auth is required to access application. Example config.js snippet,

```
module.exports = {
  auth: {
    username: 'test_username',
    password: 'test_password',
  }
};
