### ISSUE TITLE
Map Rotation and Default Map

### ISSUE THREAD

**Issue by m1ndgames** [Dahlgren/arma-server-web-admin#6]
Please implement a mission class editor, so we can set up map rotations and a default map.

**Comment by Dahlgren** [comment]
This is definitely on the priority list, it depends on https://github.com/Dahlgren/node-arma-server/issues/8 being finished first :)

**Comment by Dahlgren** [comment]
This should be done really soon I hope. Here's a WIP screenshot of the new missions tab for a server

<img width="1172" alt="screen shot 2015-08-26 at 13 26 12" src="https://cloud.githubusercontent.com/assets/288631/9514893/eec6be38-4c9d-11e5-9433-460d9dfbc8fc.png">

**Comment by Dahlgren** [comment]
Fixed with @daaefa4fa170bb6cac402e623ae4dfe4d6937ec6
