### ISSUE TITLE
Mission uploading silently failing(?)

### ISSUE THREAD

**Issue by SSederberg** [Dahlgren/arma-server-web-admin#60]
Hello, whenever I try to upload a pbo mission to our box, the upload seems to fail, as the list of missions doesn't update and it's not in the folder holding the missions. No errors are thrown as well.

Some Info:
- Running Windows Server 2016
- Running an FTP, ARMA 3, and Teamspeak 3 server
- Is installed as a windows service.
- When uploaded via FTP, it sees the mission.

**Comment by Dahlgren** [comment]
Check the bottom of the mission list. The list isn't properly reordered after mission upload currently.

**Comment by Dahlgren** [comment]
Is there any logged request in the backend output?

**Comment by Dahlgren** [comment]
Also make sure you are using the latest version, there was an issue after updating to Express 4 which made mission uploads silently fail

**Comment by SSederberg** [comment]
I believe we are using the latest version, and the mission list has no new entries after uploading, even at the bottom.  I will talk with our admin about all of these possibilities and get back to it when possible.

**Comment by Dahlgren** [comment]
Please do :)

**Comment by SSederberg** [comment]
So I suspect our file permissions were extremely screwed with, as our box required an entire reinstall (for more than just that, however), and the unit I was apart of has basically disolved. It's safe to assume that it was something on our end, as we had mutliple RDP accounts being used and many of them didn't understand what they were doing. So because of that I no longer have this issue.
