### ISSUE TITLE
Seperated MPmissions folder

### ISSUE THREAD

**Issue by CrosShadow** [Dahlgren/arma-server-web-admin#65]
Hey there :)

Is there a way to set other Mpmisions folders for varius server instances? Our Publiceser start with the same  mission as the Clan servers.

This tool is very nice and easy to use. Good work ! :)

Best Reagard Crossi

**Comment by Dahlgren** [comment]
I don't think Arma supports more than one mpmissions folder without having multiple copies of the Arma directory?

**Comment by CrosShadow** [comment]
Hi :)

Okay you got it .. there is now way at the moment .. Sorry for that :/

**Comment by CrosShadow** [comment]
I have a second question..

Is there a way tho create an Api with the server Infos ? On Json ? :)

CrosShadow

**Comment by Dahlgren** [comment]
All data is available as JSON endpoints.

Mods: `$serverUrl/api/mods`
Servers: `$serverUrl/api/servers`
