### ISSUE TITLE
Headless Clients won't connect

### ISSUE THREAD

**Issue by ToasterBR** [Dahlgren/arma-server-web-admin#70]
Hi all, hi @Dahlgren 

After the #39 , the HC's aren't connecting to the main web server. 
After some investigation, I believe the problem is the template (`config.tpl`) in the [node arma server library](https://github.com/Dahlgren/node-arma-server/blob/master/templates/config.tpl), responsible to write a server config to the spawned server.

```
headlessClients[] = {
  <% _.forEach(headlessClients, function(client) { %>
    "<%= client %>",
  <% }) %>
};
```
```
localClient[]={
  <% _.forEach(localClient, function(client) { %>
    "<%= client %>",
  <% }) %>
};
```

Using this way, both `headlessClients` and `localClient` would be inserted with a comma in the end, like this:

```
headlessClients[] = {
  
    "127.0.0.1",
  
};
```
```
localClient[]={
  
    "127.0.0.1",
  
};
```
Also, I inserted `battleyeLicense = 1;` in the template as some guides recommend you to do it but I don't know if this will be of any difference.

To make this work again, I changed the template to:
 ```
headlessClients[] = {<% _.forEach(headlessClients, function(client) { %>"<%= client %>"<% }) %>};
```
```
localClient[]={<% _.forEach(localClient, function(client) { %>"<%= client %>"<% }) %>};
```

After this change, the HCs were able to connect again in the server.

Server is Windows 10, by the way.

Thanks!

**Comment by Dahlgren** [comment]
That's odd, I can use multiple HCs without any issues. Tested on Windows 10. Works fine with and without BattleEye enabled. Do you have any custom parameters or other quirks?

*Server*
![server](https://user-images.githubusercontent.com/288631/30515025-2b061fd2-9b21-11e7-84eb-fe2b81f57645.PNG)

*HC1*
![hc](https://user-images.githubusercontent.com/288631/30515032-3fc87258-9b21-11e7-9dce-a05865399aa0.PNG)

**Comment by ToasterBR** [comment]
Well, that's strange... 
Tried to undo my modifications and it worked... 
I believe this could be a local problem, so I will close this issue :)
Thanks for the help, @Dahlgren!
