### ISSUE TITLE
Possibility to use own config

### ISSUE THREAD

**Issue by NemesisRE** [Dahlgren/arma-server-web-admin#8]
Hi,
this is such a great tool!

Would it be possible add Fields to use an own config and baseconfig so that the server startup would use the paths to configs

```
arma3server -port=2302 -cfg=PATH_TO_BASIC_CFG -config=PATH_TO_SERVER_CFG -noSound -world=empty
```

Or have a tab for expert settings and one for the current configuration

in the expert tab there would be Fields for:
- Basic config
- Server config
- additional Startup paramter

regards
Steven

**Comment by Dahlgren** [comment]
Hi!

Thanks for the kind words, it's great to get some feedback :)

`-noSound` and `-world=empty` is currently hardcoded as default options for servers and headless clients. `-config` is currently used to pass most settings set in the web admin. Network Configuration will be added once https://github.com/Dahlgren/node-arma-server/issues/4 is resolved, that would use the `-cfg` parameter.

Additional startup parameters is something that definitely should be added. I've added an issue to the underlying server module here, https://github.com/Dahlgren/node-arma-server/issues/13

I guess the `-cfg` and `-config` could be overridden by passing them as additional options. Most settings in the Web UI would then also be replaced but I guess that's the desired effect so it should be fine :)

**Comment by NemesisRE** [comment]
The direction you are going with six support, steam update and the customization options for the server is making this project to best tool for arma server administrators or even for future steam game servers.

Is the current implementation of Six automatically updating the mod after they are installed?

**Comment by Dahlgren** [comment]
No, the mods must be manually updated but any mod with a more recent release will have an "Update" button on it. This is to avoid any surprise update where a release breaks backwards compatibility.

There is currently a bug where the list of mods isn't refreshed automatically and there is no button to manually refresh it. I'll create an issue for that.

**Comment by NemesisRE** [comment]
Thats nice.

I can't find the API documentation of Six but in their client they have the possibility to define the version of the mod to be used, maybe this would be also a good addition.
What also would be great is the use of collections in the download area and the server configuration, instead of clicking every single mod just click the collection to use, but again I don't know if the API is usable for this.

**Comment by Dahlgren** [comment]
Downloading a specific version is definitely doable, the current implementation is only downloading the latest but that should be easy to extend. I've added an issue on the Play withSix module, https://github.com/Dahlgren/node-playwithsix/issues/14

Collections has been requested by a friend as well but I have yet to find a good API endpoint to work with. I guess I should have a second look at it :) https://github.com/Dahlgren/node-playwithsix/issues/15

**Comment by NemesisRE** [comment]
Ok one last issue... Where is you donation button :)

**Comment by Dahlgren** [comment]
Specifying additional startup parameters are now a separate ticket #25. I'll close this one since it has been split into separate tickets.
