### ISSUE TITLE
Trying to delete a mod installed from Steam Workshop does not work

### ISSUE THREAD

**Issue by Gehock** [Dahlgren/arma-server-web-admin#87]
I tested the steam-workshop-mod branch by installing [CBA_A3](https://steamcommunity.com/sharedfiles/filedetails/450814997). When I'm trying to delete the mod, the mod disappears from the page but I get ```DELETE /api/mods/450814997 500 0.225 ms - 2``` in the server log. The mod files are still there and the mod reappears in the mod list after a page refresh.

**Comment by Dahlgren** [comment]
No, deletion is not yet implemented, https://github.com/Dahlgren/node-arma-steam-workshop/issues/12

If the metadata is not cleaned up it's impossible to download it again due to limitations in steamcmd

**Comment by Gehock** [comment]
Alright! Tried to search for related issues but didn't realise I should search node-arma-steam-workshop as well.

**Comment by Dahlgren** [comment]
Should be done soonish I hope :)

**Comment by flexgrip** [comment]
@Dahlgren - Mind some help here or are you already working on it?

**Comment by flexgrip** [comment]
Also, what do I have to delete to clear the cache? I think I downloaded CBA, deleted it manually and now it redownloads it but your tool can't see it... even though its in the folder with the rest of the workshop mods.

**Comment by Dahlgren** [comment]
Mods only show if there is a valid meta.cpp.

The only caching is Steam’s workshop cache which prevents downloads if it thinks it’s already downloaded.

**Comment by flexgrip** [comment]
I think I figured it out. Can't remember what file it was, but it had all the mods in it. Once I deleted it, it started working again.

**Comment by Dahlgren** [comment]
Yes, as stated in the linked ticket the metadata file must be updated if any changes are done manually to Workshop files or else everything breaks when using the steamcmd tool.

**Comment by flexgrip** [comment]
So I ran out of disk space while updating a mod and had to kill the process to attach a new disk and get more space. Now that I've got more space, I can download other mods, but that specific mod refuses to download again. It has a meta.cpp and everything seems fine. I've deleted tons of cached and manifest files from the steam directory.

1. Do you know any way I can unfuck steamcmd so that it'll download the mod again?

2. Is there a steamcmd command I can run manually to update the server and the workshop items?

Thanks D :)

**Comment by flexgrip** [comment]
Sorry. To clarify. LGSM runs updates to update the server itself. Wondering if you know of a way to either manually update the workshop mods via steamcmd or if you have any sort of cron job to do it through your tool. Maybe just re-install it and it'll update? Dunno.

**Comment by Dahlgren** [comment]
Mod deletion has been added to the `feature/steam-workshop-mods` branch
