### ISSUE TITLE
multi mission upload unreliable

### ISSUE THREAD

**Issue by McDiod** [Dahlgren/arma-server-web-admin#91]
Chrome 61.0.3163.100

* upload succeeds, but webinterface doesn't update, even after clearing cache
* upload fails, no message or anything, files just don't get uploaded
* upload stops after successfully uploading the first few files

This is what I observed in a few tries. It doesn't seem to matter if you select a single or multiple files for upload. Further testing soon.

**Comment by Dahlgren** [comment]
Any steps to reproduce? Any specific missions? Haven't heard any other reports, especially none from our own community. Permission issues on your server?

**Comment by McDiod** [comment]
Just tested it again. Selected 17 files started upload >> infinite upload button animation.

I'm not sure how much difference there is between our live version and the master.
https://github.com/gruppe-adler/arma-server-web-admin

**Comment by Dahlgren** [comment]
Tested uploading 10 missions at the same time without issue to our instance. Do you have any specific missions that triggers the issue?

**Comment by McDiod** [comment]
Just did some more testing. It looks like this issue is actually unaffected by the number of missions uploaded at once, but by the total file size.

One 20MB mission will fail just like 20 1MB missions. The threshold at which this happens seems to be blurry, maybe hinting at time being the deciding factor.

**Comment by McDiod** [comment]
CC @Fusselwurm

**Comment by Dahlgren** [comment]
Are you guys running Nginx or something in front of the manager? What are the defined limits for POST body if so?

**Comment by Fusselwurm** [comment]
> `        client_max_body_size 10M;     `

*/me quietly slinks away*

**Comment by Dahlgren** [comment]
I can close this then? ;)

**Comment by Fusselwurm** [comment]
@McDiod increased from 10M to 100M 
@Dahlgren yes, close plz  :sweat:
