### ISSUE TITLE
Cannot run two servers at once [linux]

### ISSUE THREAD

**Issue by flexgrip** [Dahlgren/arma-server-web-admin#96]
Hello,

Is there anything we need to do to get two servers running at once from the same machine? If I start one instance of the arma 3 server, it works. But when I try to start the second, I get:

```
 5:44:50 SteamAPI initialization failed. Steam features won't be accessible!
 5:44:50 Cannot register unknown string STR_3DEN_CAMERA_NAME
 5:44:50 Cannot register unknown string STR_DIFF_SCENE_ONLY
 5:44:50 Cannot register unknown string STR_DIFF_SCENE_AND_MAP
 5:44:50 Initializing stats manager.
 5:44:50 Stats config disabled.
 5:44:50 sessionID: ff4678180f7d6c84f39c43c08f3aad7860d19b8b
 5:44:51 ../lib/Network/networkServer.cpp ClearNetServer:NOT IMPLEMENTED - briefing!
Cannot open file '/home/arma3server/serverfiles/workshop/steamapps/workshop/content/107410/843632231\addons\rhssaf_m_weapon_m76'
 5:44:51 Critical:Destroying running thread!
 5:44:51 Critical:Destroying running thread!
 5:44:51 Critical:Destroying running thread!
 5:44:51 Critical:Destroying running thread!
```

Is this a linux, file lock issue or something that can be done from your tool to fix it? Thanks again man... I got everything else working great from linux on the steam workshop branch. This is going to save me so much time :) 👍

**Comment by flexgrip** [comment]
So it looks like this is just a general issue with arma. The only problem is, this tool only specifies one arma3server binary. So unless there's a way to specify which server profile uses which binary, it'll never work.

Am I right in saying that each server created in this tool would need to be able to specify a separate copy of the arma3server binary? I'm reading that it may be as simple as making a copy of arma3server and then launching using the copy to get two at once. We are already able to specify different configs with your tool. And profiles as well.

**Comment by Fusselwurm** [comment]
I have no problems running half a dozen server instances from the same binary – on Linux.

But we're not using Steam Workshop items, and *that's* what your problem seems to be  related to  /shrug

**Comment by flexgrip** [comment]
Hmm @Fusselwurm. I hope you're right. There's nothing in the logs that tells me why it can't launch. 

I'm about to give up running workshop stuff on linux. Everything works. But it's a crap shoot as to whether or not people crash while joining. It seems to like missions that are pbo'd instead of just in a folder. But then at the same time people are getting all kinds of memory issues.

I'm going to recreate the same setup in my windows server using Dahlgren's tools and see if there's a difference.

**Comment by Dahlgren** [comment]
Your rpt log seems like a corrupt addon file, verify your mod files
