### ISSUE TITLE
No such file or directory, scandir

### ISSUE THREAD

**Issue by diaverso** [Dahlgren/arma-server-web-admin#99]
Os: Windows server 2012 R2
When making "npm start" I get these error:

https://i.imgur.com/94DQWnj.png

configuration code: 

module.exports = {
  game: 'arma3', // arma3, arma2oa, arma2, arma1, cwa, ofpresistance, ofp
  path: 'C:\Users\root\Desktop\ServerArma3',
  port: 3000,
  host: '(omitted)', // Can be either an IP or a Hostname
  type: 'windows', // Can be either linux, windows or wine
  parameters: [ // Additional startup parameters used by all servers
    '-noSound',
    '-world=empty'
  ],
  serverMods: [ // Mods used exclusively by server and not shared with clients
    '@mod1',
    '@mod2',
  ],
  admins: [], // add steam IDs here to enable #login without password
  auth: { // If both username and password is set, HTTP Basic Auth will be used. You may use an array to specify more than one user.
    username: 'simulacion', // Username for HTTP Basic Auth
    password: 'a1234567', // Password for HTTP Basic Auth
  },
  prefix: "[ES]", // Prefix to all server names
  suffix: "", // Suffix to all server names
  logFormat: "dev", // expressjs/morgan log format
};

**Comment by Dahlgren** [comment]
Due to how Windows handles paths compared to other operating systems and how Node handles strings the path must be typed with double backslahes.

`path: 'C:\Users\root\Desktop\ServerArma3',`
should be
`path: 'C:\\Users\\root\\Desktop\\ServerArma3',`

**Comment by diaverso** [comment]
Thanks :)
